version: "3.3"
services:
  shd:
    build:
      dockerfile: Dockerfile
      context: ./
    env_file:
      - ./telegram-bot.secret
    volumes:
      - ./savemodel/best_model.pth:/app/SHD/savemodel/best_model.pth
