version: "3.3"
services:
  shd:
    build:
      dockerfile: Dockerfile
      context: ./
    env_file:
      - ./telegram-bot.secret
    volumes:
      - ./savemodel:/app/SHD/savemodel
    restart: unless-stopped
